### ISSUE TITLE
7. Update existing cards with detailed information

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#10]
## Value Proposition
As a user, I want to update my existing cards after I played a match/training so that I can see on these specific cards the additional added informations 
## Description
![Image](https://user-images.githubusercontent.com/104638689/197215862-3fbfd871-3d1b-4d77-b1ad-a26099ccee86.png)

## Acceptance Criteria
- [x] Display the additional added information on the card

## Tasks
- [x] Create new branch feat/updatecardwithdetails
- [x] Onsubmit update the gameList useState with the detail additional information
> "result"
> "firstsetplayerone:
> "firstsetplayertwo: 
> "secondsetplayerone: 
> "secondsetplayertwo: 
> "thirdplayerone: 
> "thirdsetplayertwo: 

- [x] Create a new component e.g. CardResults
- [x] Add the CardResult to the initial card component if the user at least selected "won" or "lost" in the carddetail form
- [x] Add some basic styling (see pic)

### new example array before card edit:
```
[
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Max", 
"date": "22.01-10",
"time": "19:00",
"place": "Rothof",
"court": "Carpet",
"results": {
                 "gameresult": "",
                 "set": [
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
               ]
}
}
{
"id": Math.random().toString(20).substring(3)
"type": "Training", 
"name": "Sonja", 
"date": "22.01-15",
"time": "20:00",
"place": "Fidelopark",
"court": "Sand",
"results": {
                 "gameresult": "",
                 "set": [
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
               ]
}
}
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Steffi", 
"date": "22.01-20",
"time": "10:00",
"place": "Sportscheck",
"court": "Gras",
"results": {
                 "gameresult": "",
                 "set": [
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
               ]
}
}
]
```

### new example array after card edit:
```
[
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Max", 
"date": "22.01-10",
"time": "19:00",
"place": "Rothof",
"court": "Carpet",
"results": {
                 "gameresult": "won",
                 "set": [
                       {
                            Player1: "6",
                            Player2: "2", 
                       }
                       {
                            Player1: "1",
                            Player2: "3", 
                       }
                       {
                            Player1: "6",
                            Player2: "1", 
                       }
               ]
}
}
{
"id": Math.random().toString(20).substring(3)
"type": "Training", 
"name": "Sonja", 
"date": "22.01-15",
"time": "20:00",
"place": "Fidelopark",
"court": "Sand",
"results": {
                 "gameresult": "won",
                 "set": [
                       {
                            Player1: "6",
                            Player2: "0", 
                       }
                       {
                            Player1: "0",
                            Player2: "6", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
               ]
}
}
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Steffi", 
"date": "22.01-20",
"time": "10:00",
"place": "Sportscheck",
"court": "Gras",
"results": {
                 "gameresult": "lost",
                 "set": [
                       {
                            Player1: "6",
                            Player2: "1", 
                       }
                       {
                            Player1: "1",
                            Player2: "6", 
                       }
                       {
                            Player1: "1",
                            Player2: "6", 
                       }
               ]
}
}
]
```

**Comment by Ozanyurdakul98** [comment]
after onSubmit the new formData should rather update the existing data then just be saved. Just change save to update.
just my 2 cents

**Comment by AHen-C0de** [comment]
Hey,
nice and short user story!
I would arrange the sets in your gameList state as an array as follows:
```js
"results": {
                 "gameresult": "",
                 "set": [
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
                       {
                            Player1: "",
                            Player2: "", 
                       }
               ]
}
```
...this way, you can easily map across the sets for rendering. If a user does not enter results for any set, you can write "undefined" into the position in the array and catch this during the rendering process.

**Comment by PhilippWeiss85** [comment]
Hey Angela, thanks for the great idea! I ll update my story with your suggestion.
