### ISSUE TITLE
4. Add basic stylings

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#15]
## Value Proposition
As a User, I want the app look admirable so that it is also visual pleasing to use it.
## Description
App should use some basic styling rules for borders, colors and sizes for all used elements to enhance the ux
## Acceptance Criteria
- [x] Add a basic structure/layout of the app
- [x] Add color schema

## Tasks
- [x] add new branch feat/styling-basic
- [x] add new primary color
- [x] add new secondary color
- [x] define margin & padding
- [x] define background
- [x] define borders & radius
- [x] set font size for headline, paragraphs and form elements

**Comment by gacsphere** [comment]
Hi Philipp, 
your value proposition sounds very funny! :-D As future employers might read this, maybe you want to overthink the first sentence so that it sounds more serious. But this is your decision, not a must ;-)

Instead of "defines spaces" you could write "define padding and margins".

I'm not sure if your acceptance creteria "Add basic stylings" is correct. It sounds a bit like a summary of all tasks. Maybe something in this direction would be good: Well structured visual styling to enhance the users experience and make the app easily understandable/usable.
