### ISSUE TITLE
8. Add localStorage for data persistence

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#19]
## Value Proposition
As a user, I want that my added/deleted matchcards persists after my session so that still see them when returning to the app.
## Description
Adding localStorage to persist data

## Acceptance Criteria
- [ ] After reloading/revisiting the app, the changes on cards previously done still persists in the app

## Tasks
- [ ] Create new branch feat/localstorage
- [ ] Create new folder "hooks"
- [ ] create localStorage.js file
- [ ] Add predefined code to localStorage hook
- [ ] Set localStorage hook on gameList Array

predefined code:
```
import {useCallback, useEffect, useState} from 'react';

/**
 * A hook to use localStorage with SSR.
 *
 * Make sure that localStorage and state do not conflict with each other.
 * Only update the state if no initialState was read from localStorage.
 *
 * @param {string} key
 * @param {unknown} initialState
 * @returns {[unknown, function(value: unknown): void | function(fn: function(previousValue: unknown): void): void]}
 */
export default function useLocalStorage(key, initialState) {
    // Set the desired initialState
    const [state, setState] = useState(initialState);

    // Provide a custom setter function that updates the state and writes to localStorage
    const setStateAndLocalStorage = useCallback((callbackOrValue) => {
        setState(previousValue => {
            // The value might be a callback with the previousValue
            const nextValue = typeof callbackOrValue === "function" ? callbackOrValue(previousValue) : callbackOrValue;
            // Set the localStorage here (inside the original setter)
            window.localStorage.setItem(key, JSON.stringify(nextValue));
            return nextValue;
        })
    }, [key]);

    // Read the localStorage from the client
    useEffect(() => {
        const stored = window.localStorage.getItem(key);
        // When the stored value === null
        // Then the key does not exist, and we don't want to perform an update
        if (stored !== null) {
            setState(JSON.parse(stored))
        }
    }, [key]);

    return [state, setStateAndLocalStorage]
}

**Comment by AHen-C0de** [comment]
LGTM!
Just a comment regarding your previous user story: 
If you want also the game results to be saved in local storage, I would add those to your gameList state and not create an extra state for the results (As you wrote down both options in ur user story ^^)

**Comment by PhilippWeiss85** [comment]
> I would add those to your gameList state and not create an extra state for the results (As you wrote down both options in ur user story ^^)

Thanks for the feedback! Will do :)
