### ISSUE TITLE
9. Add quantity counter to gamecard List

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#20]
## Value Proposition
As a user, I want see how many cards & categories and I have so that I can keep track of my progress.
## Description
// Insert Wire Frame
## Acceptance Criteria
- [ ] Gamecard page shows the total quantity of cards
- [ ] Gamecard page shows the quantity of match cards
- [ ] Gamecard page shows the quantity of training cards

## Tasks
- [ ] Create new branch feat/gamelistcounter
- [ ] step by step
- [ ] to be executed by developer
