### ISSUE TITLE
11. Basic Navigation

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#21]
## Value Proposition
As a User, I want be able to navigate freely within the app so that I can cancel inputs or move to previous pages with one click.
## Description
Add basic navigation features to the app so you have the ability to reach every item

## Acceptance Criteria
- [x] Displays cancel/navigation button everywhere a navigation input could be necessary (Forms, Detailpages, Mainpages and so on)
- [x] Define routing between these pages
- [x] Display sticky footer navigation for gameplan & lessons

## Tasks
- [x] Create a new branch feat/navigation
- [x] Add Entry Page
- [x] Add cancel/navigation buttons to the necessary components/pages
- [x] Add routing (mostly back routing) to the new buttons

**Comment by AHen-C0de** [comment]
LGTM!
