### ISSUE TITLE
9. Technique lessons page

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#22]
## Value Proposition
As a user, I want to have a lessons section in the app so that I can remind myself of the basic steps for the different techniques.
## Description
<img width="533" alt="Screenshot 2022-10-23 at 11 28 28" src="https://user-images.githubusercontent.com/104638689/197384717-abc73d56-00f2-496f-992d-a7a84e4fd22a.png">

## Acceptance Criteria
- [x] A new page "/lessons" can be accessed 
- [x] Lessons page contains links to the six different basic techniques
- [x] Every page show additional information about the specific technique

## Tasks
- [x] Create a new branch feat/lessons
- [x] Create a new page lessons.js
- [x] Add basic layout and content to the lessons.js page (see wireframe)
- [x] Create dynamic [name].js in lessons page folder
- [x] Add Headline of the selected technique an dummy content to the pages 
- [x] Use GetStaticProps for the dynamic technique pages

**Comment by AHen-C0de** [comment]
LGTM!
