### ISSUE TITLE
8. Add localStorage for data persistence

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#25]
## Value Proposition
As a user, I want that my added/deleted matchcards persists after my session so that still see them when returning to the app.

## Description
Adding localStorage to persist data

## Acceptance Criteria
- [ ] After reloading/revisiting the app, the changes on cards previously done still persists in the app

## Tasks
- [x] Create new feat/zustandandlocalstorage branch
- [x] Create store folder and useStore.js file
- [x] npm install zustand
- [x] Create callback function useStore
- [x] Return initial globel state as object
- [x] Create setter functions
- [x] Update state management in pages/components
- [x] Add persist/localStorage

**Comment by Roland-Hufnagel** [comment]
Hey Philipp, thats a good value proposition for a developer but I think a developer is not a user.

**Comment by Roland-Hufnagel** [comment]
That looks brilliant
