### ISSUE TITLE
10. Implement MongoDB

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#29]
## Value Proposition
As a user, I want to have access to my stored data from any device/location so that can use them independently.
## Description
Set up connection to database and persist data in there

## Acceptance Criteria
- [ ] User have access to his stored data independently of the device/location

## Tasks
- [x] Create branch feat/database
- [x] Create new DB & Collection
- [x] Insert example array in collection
- [x] Add .env.local file
- [x] Add db.Connect.js in lib
- [x] Add models folder/files

**Comment by Roland-Hufnagel** [comment]
nothing to say. Perfect and clean
