### ISSUE TITLE
2. Add click functionality and href to the first category page

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#3]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >
As a user, i want to be able to visit/view the detail-page of the gameplan category so that i can get further informations about the content.

## Description
![main-to-gameplan](https://user-images.githubusercontent.com/104638689/195832556-394812f1-ef2d-4d51-822c-0517df3cbc9e.png)

## Acception Criteria
- [ ] Make the category gameplan-container clickable
- [ ] There needs to be some kind of effect so that the user can see, that the container is clickable
- [ ] Create a dummy detail page of the gameplan category
- [ ] Set routing 

## Tasks
- [ ] create a new page for gameplan category
- [ ] add click functionality to the gameplan-container
- [ ] set routing on click to the gameplan page.
- [ ] add hover and/or clickeffect to the gameplan-container
