### ISSUE TITLE
12. Add Statistics

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#31]
## Value Proposition
As a user, I want to see my game statistics so that can keep track my progress.
## Description
![Screenshot 2022-10-31 at 11 57 31](https://user-images.githubusercontent.com/104638689/198993000-b5695d3e-7ced-4329-9651-b74ec58c7d95.png)

## Acceptance Criteria
- [x] Displays statistics for the existing games
- [x] Line chart for games played in the last month
- [x] Bar chart for comparison won/lost

## Tasks
- [x] Create new branch
- [x] Install chart.js
- [x] Import and register necessary charts
- [x] Create chart component
- [x] Add existing data to the carts
- [x] Add basic styling to the charts

**Comment by AHen-C0de** [comment]
LGTM! Depending on what your scale of the x-axis on the first graph is, you might need another function to calculate the amount of played games within your time frame from your stored data, that only have a date, I guess.
