### ISSUE TITLE
16. Improve styling

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#32]
## Value Proposition
As a user, I want to have a good looking app so that I it is a pleasure to look at it.
## Description
Improve Styling:
- Set color range
- Improve layout on mobile devices

## Acceptance Criteria
- [x] Displays app with new styling

## Tasks
- [x] Create new branch
- [x] Add color schema to root:
- [x] Edit font sizes
- [x] Add new google font
- [x] Change visual appearance of some pages/components

**Comment by AHen-C0de** [comment]
LGTM!
If you have a figma preview, I would add it here, too. ;)
