### ISSUE TITLE
14. Modal Component

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#37]
## Value Proposition
As a User, I want to see an overlay with additional information when something went wrong/need confirmation with my input so that I have a better understanding of whats going on.
## Description
![Screenshot 2022-11-07 at 12 26 02](https://user-images.githubusercontent.com/104638689/200299094-d8a220c3-0db5-4093-8aa4-cc2838f210cb.png)

## Acceptance Criteria
- [x] Instead of window errors an overlay is shown to the user
- [x] Overlay is flexible depending on the place it appears (e.g. form, deletecard)
- [x] The user have to confirm/cancel the overlay to continue to use the app
## Tasks
- [x] Create new branch feat/modal
- [x] Add modal component 
- [x] Add Text to modal component
- [x] Add Button components to modal component
- [x] Add modal styling
- [x] Replace window.errors in form with modal
- [x] Add Modal as confirmation blocker to the delete card function

**Comment by philmetscher** [comment]
LGTM. Only advice from me: You could add some more Information about `Add modal component`. For Example:
- [ ] create `Modal component`
  - [ ] add Text
  - [ ] add `Button components`
