### ISSUE TITLE
15. Image upload

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#39]
## Value Proposition
As a User, I want to be able to upload my opponent's Image so that I see a more personalized app.
## Description
![Screenshot 2022-11-08 at 11 06 08](https://user-images.githubusercontent.com/104638689/200536223-696679d1-17c6-4602-a7d2-3e930442a5d9.png)

## Acceptance Criteria
- [x] Display a image upload input field in the create card form (not mandatory)
- [x] Uploaded image is displayed on the created gamecard

## Tasks
- [x] Create new branch feat/cloudinary
- [x] Install cloudinary and formidable
- [x] Update next.config.js images with cloudinary domain
- [x] Update .env.local with cloudinary variables
- [x] Create new upload api
- [x] Update Form component
- [x] Update GameCard component
