### ISSUE TITLE
1. Add card components to gameplan page

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#4]
## Value Proposition
As a user i want to see my upcoming matchups on a page so that I can keep track of them.

## Description

![Image](https://user-images.githubusercontent.com/104638689/196029931-8a9a7875-383c-4b2f-b31a-2da059a6b5cb.png)

## Acceptance Criteria
- [x] Display headline: "Your Gameplan"
- [x] User can see cards with the following information
> type of match
> name
> date
> time
> place 
> type of court  

## Tasks
- [x] create a feat/gameplan branch
- [x] create a gameplan.js page
- [x] create a GameCard.js component
- [x] add example array for the matchup cards
- [x] map over example array

example array:
```
[
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Max", 
"date": "22.01-10",
"time": "19:00",
"place": "Rothof",
"court": "Carpet",
}
{
"id": Math.random().toString(20).substring(3)
"type": "Training", 
"name": "Sonja", 
"date": "22.01-15",
"time": "20:00",
"place": "Fidelopark",
"court": "Sand",
}
{
"id": Math.random().toString(20).substring(3)
"type": "Match", 
"name": "Steffi", 
"date": "22.01-20",
"time": "10:00",
"place": "Sportscheck",
"court": "Gras",
}
]
```

**Comment by philmetscher** [comment]
I think the tasks are very specific. The tasks should be written in such a way that everyone understands them ( as I have understood it).
