### ISSUE TITLE
16. Sort function

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#41]
## Value Proposition
As a user, I want to sort my gamecards (e.g. by type,  by result, by name) so that have a better overview of my games.
## Description
![Screenshot 2022-11-09 at 11 38 51](https://user-images.githubusercontent.com/104638689/200808891-2ea34f4f-add5-4acb-86df-fd5ab042a61e.png)

## Acceptance Criteria
- [x] Displays a sorting button on the gamelist page  
- [x] user can sort the gamecards on click by type(match/training), by result(won/lost) and by name

## Tasks
- [x] Create new branch feat/sortfunction
- [x] Create sort component
- [x] Add necessary sort function
- [x] Add sort component to gamelist

**Comment by philmetscher** [comment]
LGTM! have fun 😄
