### ISSUE TITLE
2. Add form to create new matchups

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#5]
## Value Proposition
As a user I want to create new matchups so that I can see them on my gameplan page

## Description
![Image](https://user-images.githubusercontent.com/104638689/196459679-f6847539-c27c-454f-866c-ea08133dc4b6.png)

## Acceptance Criteria
- [ ] The user should be able to add the required contents from gameplan card and add a new, filled card on click:
> **Type:**
> - [x] radio buttons: Match/Training

> **Add your opponents:**
> - [x] Text

> **Choose your date:**
> - [x] Date picker (calender) - yy.mm.dd

> **Pick your place:**
> - [x] dropdown menu with pre defined places

> **Choose your date:**
> - [x] radio buttons: Sand, Carpet, Concrete

- [x] button to create a new card

## Tasks

- [x] create a new branch feat/form
- [x] Create Form Component
- [x] Create form-page
- [x] Create Labels and input types for the different form fields
- [x] Create a button component
- [x] Add a submit button
- [x] Onsubmit add the new form data to the example array to create a new card

**Comment by CathrinTruchan** [comment]
Looks very good to me :)

**Comment by PhilippWeiss85** [comment]
- added required attributes to the form to prevent that users add empty cards.
- right now there is no connection between the form and the gameplan page, therefore another example array and gamecard mapping and adding cards is executed on the form page.
