### ISSUE TITLE
3. Connect gameplan page with form page

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#6]
## Value Proposition
As a user, I want to navigate to the form page from the gameplan page (and vince versa) so that I dont have to use the URL to access the pages.
## Description
![image](https://user-images.githubusercontent.com/104638689/196032522-d63b1963-ee8c-4090-9635-83ea9f21b7de.png)

## Acceptance Criteria
- [x] Displays "Add New Match" button on the gameplan page
- [x] The "Add New Match" button on the gamplan page should route to the form page
- [x] The form page needs a cancel button
- [x] The cancel button should route the user back to the gameplan back

## Tasks
- [x] create new feat/formroute branch
- [x] Implement the button component from #5  as "Add New Match" button to the gameplan page
- [x] Route on click to the form page
- [x] Implement the button component from #5 as "Cancel" button to the form page
- [x] route on click back to the gameplan page

**Comment by F-Kirchhoff** [comment]
Hey Phillip, this is looking very good. I only have some wording suggestions: 
- instead of "there needs to be" you can write: "displays 'new match' button"
- you missed some tasks (if you didn't already done so in a previous user story): 
  - add button component
  - implement button component as 'add new match' button 
  - implement button component as 'cancel' button

**Comment by PhilippWeiss85** [comment]
> Hey Phillip, this is looking very good. I only have some wording suggestions:
> 
> * instead of "there needs to be" you can write: "displays 'new match' button"
> * you missed some tasks (if you didn't already done so in a previous user story):
>   
>   * add button component
>   * implement button component as 'add new match' button
>   * implement button component as 'cancel' button

Hi Felix, thank you for your feedback! I have updated the wordings and added a link to the story where the button component is created

**Comment by F-Kirchhoff** [comment]
wow, good practice to link the other user story!
