### ISSUE TITLE
13. Component testing

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#7]
## Value Proposition
As a developer, I want to test if my components work properly so that users got an errorless experience.
## Description
Add tests to the app

## Acceptance Criteria
- [x] The tests don't fail
- [x] The test should at least test 3 different values

## Tasks
- [x] Create new branch feat/testing
- [x] write a test for rendering the gamelist
- [x] write a test for deleting games on gamelist
- [x] write a test for adding games to gamelist
- [x] write a test for update the game results in gamecards
