### ISSUE TITLE
5. Delete existing cards

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#8]
## Value Proposition
As a user, I want to have the ability to delete cards so that I can remove matchups that I dont need anymore (e.g. due the cancelation of match).
## Description
![image](https://user-images.githubusercontent.com/104638689/196033713-b4712e0b-7cfb-46d8-9e85-9959ea112071.png)
## Acceptance Criteria
- [x] Display a delete icon/button on every card
- [x] The user can remove any card from the gameplan page by clicking on the delete button
## Tasks
- [x] Create branch feat/deletecard
- [x] Create a new "delete card" button component 
- [x] Add Delete Icon to the card component
- [x] onClick: Filter new card array without the card-id which was clicked

**Comment by F-Kirchhoff** [comment]
The 'delete icon' should be a button (maybe a new button component? If Yes, add the creation of that component to your task list!). I like that you already specified how to achieve the task of deleting a card!

**Comment by PhilippWeiss85** [comment]
> The 'delete icon' should be a button (maybe a new button component? If Yes, add the creation of that component to your task list!). I like that you already specified how to achieve the task of deleting a card!

Thank for the feedback! Added the "Create new button component" to the task list.
