### ISSUE TITLE
6. Add edit button and CardDetails

### ISSUE THREAD

**Issue by PhilippWeiss85** [PhilippWeiss85/capstone-project#9]
## Value Proposition
As a user, I want to have an edit button on my exisiting cards so that I can edit or update my existing card in the future .
## Description

![Image](https://user-images.githubusercontent.com/104638689/197490082-7d8e9645-8abf-4350-9d80-d295778b1f1a.png)

## Acceptance Criteria
- [x] The user can see and click a edit button on each card
~~- [ ] onClick: the user is redirected to a new page "edit card"~~
~~- [ ] The "edit card" page shows the card which the user clicked on top of the viewport~~

**UPDATE**
- [x] The edit button fold/unfold on click
- [x] The user add detailed informations to the card

## Tasks
- [x] Create new branch feat/editcard
- [x] Add the button component from #5 as "edit button" to the card component

~~- [ ] Create a new edit card page~~
~~- [ ] onClick: Edit button redirect the user to the edit card page~~
~~- [ ] use .find() on the cardID in the array to show the clicked card on the edit card page~~

**UPDATE**
- [x] Add a CardDetail component
- [x] Add toggleIcon
- [x] Add a function to toggle the display of the CardDetail component
- [x] Add a form with the necessary input fields to CardDetails component

--> follow up user story for button functionality: #10

**Comment by AHen-C0de** [comment]
Very nice story - detailed and short! Nothing to add. :)
